/* REGIONS / CITIES
TODO: Use JSON to update dinamically
*/
const Location = {
  ANTOFAGASTA: {
    ANTOFAGASTA: "ANTOFAGASTA:ANTOFAGASTA",
    CALAMA: "ANTOFAGASTA:CALAMA",
    MEJILLONES: "ANTOFAGASTA:MEJILLONES",
    OLLAGUE: "ANTOFAGASTA:OLLAGÜE",
    SAN_PEDRO_DE_ATACAMA: "ANTOFAGASTA:SAN PEDRO DE ATACAMA",
    SIERRA_GORDA: "ANTOFAGASTA:SIERRA GORDA",
    TALTAL: "ANTOFAGASTA:TALTAL"
  },
  ATACAMA: {
    CALDERA: "ATACAMA:CALDERA",
    COPIAPO: "ATACAMA:COPIAPO",
    TIERRA_AMARILLA: "ATACAMA:TIERRA AMARILLA"
  },
  COQUIMBO: {
    ANDACOLLO: "COQUIMBO:ANDACOLLO",
    COQUIMBO: "COQUIMBO:COQUIMBO",
    LA_HIGUERA: "COQUIMBO:LA HIGUERA",
    LA_SERENA: "COQUIMBO:LA SERENA",
    PAIHUANO: "COQUIMBO:PAIHUANO",
    VICUNA: "COQUIMBO:VICUÑA"
  },
  VALPARAISO: {
    ISLA_DE_PASCUA: "VALPARAISO:ISLA DE PASCUA"
  },
  BIOBIO: {
    CHIGUAYANTE: "BIOBIO:CHIGUAYANTE",
    CONCEPCION: "BIOBIO:CONCEPCIÓN",
    CORONEL: "BIOBIO:CORONEL",
    FLORIDA: "BIOBIO:FLORIDA",
    HUALPEN: "BIOBIO:HUALPEN",
    HUALQUI: "BIOBIO:HUALQUI",
    LOTA: "BIOBIO:LOTA",
    PENCO: "BIOBIO:PENCO",
    SAN_PEDRO_DE_LA_PAZ: "BIOBIO:SAN PEDRO DE LA PAZ",
    SANTA_JUANA: "BIOBIO:SANTA JUANA",
    TALCAHUANO: "BIOBIO:TALCAHUANO",
    TOME: "BIOBIO:TOME"
  },
  RM_SANTIAGO: {
    CERRILLOS: "REGION METROPOLITANA DE SANTIAGO:CERRILLOS",
    CERRO_NAVIA: "REGION METROPOLITANA DE SANTIAGO:CERRO NAVIA",
    CONCHALI: "REGION METROPOLITANA DE SANTIAGO:CONCHALI",
    EL_BOSQUE: "REGION METROPOLITANA DE SANTIAGO:EL BOSQUE",
    ESTACION_CENTRAL: "REGION METROPOLITANA DE SANTIAGO:ESTACION CENTRAL",
    HUECHURABA: "REGION METROPOLITANA DE SANTIAGO:HUECHURABA",
    INDEPENDENCIA: "REGION METROPOLITANA DE SANTIAGO:INDEPENDENCIA",
    LA_CISTERNA: "REGION METROPOLITANA DE SANTIAGO:LA CISTERNA",
    LA_FLORIDA: "REGION METROPOLITANA DE SANTIAGO:LA FLORIDA",
    LA_GRANJA: "REGION METROPOLITANA DE SANTIAGO:LA GRANJA",
    LA_PINTANA: "REGION METROPOLITANA DE SANTIAGO:LA PINTANA",
    LA_REINA: "REGION METROPOLITANA DE SANTIAGO:LA REINA",
    LAS_CONDES: "REGION METROPOLITANA DE SANTIAGO:LAS CONDES",
    LO_BARNECHEA: "REGION METROPOLITANA DE SANTIAGO:LO BARNECHEA",
    LO_ESPEJO: "REGION METROPOLITANA DE SANTIAGO:LO ESPEJO",
    LO_PRADO: "REGION METROPOLITANA DE SANTIAGO:LO PRADO",
    MACUL: "REGION METROPOLITANA DE SANTIAGO:MACUL",
    MAIPU: "REGION METROPOLITANA DE SANTIAGO:MAIPU",
    NUNOA: "REGION METROPOLITANA DE SANTIAGO:ÑUÑOA",
    PEDRO_AGUIRRE_CERDA: "REGION METROPOLITANA DE SANTIAGO:PEDRO AGUIRRE CERDA",
    PENALOLEN: "REGION METROPOLITANA DE SANTIAGO:PEÑALOLEN",
    PROVIDENCIA: "REGION METROPOLITANA DE SANTIAGO:PROVIDENCIA",
    PUDAHUEL: "REGION METROPOLITANA DE SANTIAGO:PUDAHUEL",
    QUILICURA: "REGION METROPOLITANA DE SANTIAGO:QUILICURA",
    QUINTA_NORMAL: "REGION METROPOLITANA DE SANTIAGO:QUINTA NORMAL",
    RECOLETA: "REGION METROPOLITANA DE SANTIAGO:RECOLETA",
    RENCA: "REGION METROPOLITANA DE SANTIAGO:RENCA",
    SAN_JOAQUIN: "REGION METROPOLITANA DE SANTIAGO:SAN JOAQUIN",
    SAN_MIGUEL: "REGION METROPOLITANA DE SANTIAGO:SAN MIGUEL",
    SAN_RAMON: "REGION METROPOLITANA DE SANTIAGO:SAN RAMON",
    SANTIAGO: "REGION METROPOLITANA DE SANTIAGO:SANTIAGO",
    VITACURA: "REGION METROPOLITANA DE SANTIAGO:VITACURA"
  }
};

module.exports = Location;
